//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTask.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public long FormId { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public bool Married { get; set; }
        public bool Animals { get; set; }
        public bool Childs { get; set; }
        public string Name { get; set; }
    }
}
